[package]
name = "plamenu-federation"
description = "HTTP signatures and federation transport for Plamenu"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
base64 = { workspace = true }
ed25519-dalek = { workspace = true }
html5ever = { workspace = true }
http = { workspace = true }
httpdate = { workspace = true }
futures-util = { workspace = true }
plamenu-ap = { workspace = true }
reqwest = { workspace = true }
rsa = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[lints]
workspace = true
