"""Build identifiable docs locally and publish their generated bytes to Pages."""

import concurrent.futures
import html
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

import tomllib

from .core import ReleaseError, Runner, clean, files, fingerprint, git, write_json
from .forge import Forge, NoRedirect

SCRIPTS = Path(__file__).resolve().parents[1]
MARKER = "build.json"


def identity(source):
    version = tomllib.loads((source / "Cargo.toml").read_text())["workspace"][
        "package"
    ]["version"]
    revision = git(source, "rev-parse", "HEAD")
    tag = "v" + version
    tags = git(source, "tag", "--points-at", revision).splitlines()
    return {
        "version": version,
        "source": revision,
        "build_number": git(source, "show", "-s", "--format=%ct", revision),
        "release_tag": tag if tag in tags else None,
        "dirty": bool(git(source, "status", "--porcelain", "--untracked-files=normal")),
    }


def stamp(destination, build):
    status = build.get("release_tag") or "development"
    if build["dirty"]:
        status += " · local changes"
    text = (
        f"Plamenu {build['version']} · {status} · Build {build['build_number']}"
        f" · Source {build['source'][:12]}"
    )
    for page in destination.rglob("*.html"):
        body = page.read_text()
        if "<main>" not in body:
            continue
        relative = Path(os.path.relpath(destination / MARKER, page.parent)).as_posix()
        banner = (
            '<aside class="docs-build" aria-label="Documentation build" '
            'style="font-size:.85em;line-height:1.6;margin:0 0 1.5em;padding:.65em 1em;'
            'border:1px solid var(--table-border-color);border-radius:4px">'
            + html.escape(text)
            + f' · <a href="{html.escape(relative, quote=True)}">Build details</a></aside>'
        )
        page.write_text(body.replace("<main>", "<main>\n" + banner, 1))
    record = {"schema": 1, "build": build, "files": files(destination)}
    record["site_sha256"] = fingerprint(record)
    write_json(destination / MARKER, record)
    return record


def build_site(source, destination, log):
    if destination.is_symlink():
        raise ReleaseError("Docs output must not be a symlink")
    source, destination = source.resolve(), destination.resolve()
    # Permit a build directory in target, or a directory outside this checkout.
    if (
        destination == source
        or destination in source.parents
        or source in destination.parents
        and source / "target" not in destination.parents
    ):
        raise ReleaseError("Docs output must not replace source files")
    if destination.exists():
        shutil.rmtree(destination)
    runner = Runner(source, log)
    runner.run("mdbook", "build", source / "docs", "--dest-dir", destination)
    record = stamp(destination, identity(source))
    runner.run(sys.executable, SCRIPTS / "check-built-doc-links.py", destination)
    return record


def enabled(config):
    value = config.get("docs", {})
    if not isinstance(value, dict) or type(value.get("enabled", False)) is not bool:
        raise ReleaseError("docs.enabled must be a TOML boolean")
    return value.get("enabled", False)


def destination(config):
    repository = config.get("docs", {}).get("repository", config.get("repository", ""))
    if not isinstance(repository, str):
        raise ReleaseError("docs.repository must be an HTTPS repository URL")
    target = Forge(repository, "")
    origin = Forge(config.get("repository", ""), "")
    if target.origin != origin.origin:
        raise ReleaseError("Docs must use the same forge as the configured repository")
    return target.repository


def settings(config):
    if not enabled(config):
        raise ReleaseError(
            "Enable [docs] in the local release config before deploying docs"
        )
    docs = config["docs"]
    url = docs.get("url", "")
    if not isinstance(url, str):
        raise ReleaseError("docs.url must be an HTTPS URL")
    parsed = urllib.parse.urlsplit(url)
    if (
        parsed.scheme != "https"
        or not parsed.hostname
        or parsed.username
        or parsed.password
        or parsed.query
        or parsed.fragment
    ):
        raise ReleaseError("docs.url must be the canonical HTTPS site URL")
    branch = docs.get("branch", "pages")
    if (
        not isinstance(branch, str)
        or branch.startswith("-")
        or subprocess.run(
            ["git", "check-ref-format", "refs/heads/" + branch],
            capture_output=True,
            check=False,
        ).returncode
    ):
        raise ReleaseError("docs.branch must be a valid Git branch")
    repository = destination(config)
    if branch in ("main", "master") and repository == config["repository"].rstrip("/"):
        raise ReleaseError(
            "Docs require a separate deployment branch in the source repository"
        )
    for name in ("repository", "token_file"):
        if not config.get(name):
            raise ReleaseError("Docs configuration missing " + name)
    if not Path(config["token_file"]).expanduser().is_file():
        raise ReleaseError("Docs token_file must name a regular file")
    return url.rstrip("/") + "/", branch


def remote_url(source, config):
    repository = destination(config)
    parsed = urllib.parse.urlsplit(repository)
    if repository != config["repository"].rstrip("/"):
        # An explicit docs repository needs no extra remote in the source checkout.
        return f"git@{parsed.netloc}:{parsed.path.lstrip('/')}.git"
    remote = config.get("git_remote", "codefloe")
    url = git(source, "remote", "get-url", "--push", remote)
    if url not in (
        repository + ".git",
        f"git@{parsed.netloc}:{parsed.path.lstrip('/')}.git",
        f"ssh://git@{parsed.netloc}{parsed.path}.git",
    ):
        raise ReleaseError(
            "Git push remote differs from the configured docs repository"
        )
    return url


def publish_tree(source, site, remote, branch, log, forge):
    """Normal pushes reject concurrent updates; identical trees reuse the commit."""
    ref = "refs/heads/" + branch
    with tempfile.TemporaryDirectory(prefix="plamenu-pages-") as temporary:
        checkout = Path(temporary)
        runner = Runner(checkout, log)
        runner.run("git", "init", "--quiet")
        for key in (
            "user.name",
            "user.email",
            "user.signingkey",
            "gpg.format",
            "gpg.ssh.allowedSignersFile",
        ):
            value = subprocess.run(
                ["git", "config", "--get", key],
                cwd=source,
                text=True,
                capture_output=True,
                check=False,
            )
            if value.returncode == 0:
                setting = value.stdout.strip()
                if key == "gpg.ssh.allowedSignersFile":
                    setting = str((source / Path(setting).expanduser()).resolve())
                runner.run("git", "config", key, setting)
        if git(source, "ls-remote", "--heads", remote, ref):
            runner.run("git", "fetch", "--quiet", remote, ref)
            runner.run("git", "checkout", "--quiet", "--detach", "FETCH_HEAD")
            if any((checkout / p).exists() for p in ("Cargo.toml", ".forgejo", "dev")):
                raise ReleaseError(
                    "Refusing to replace a source branch with generated docs"
                )
        for path in checkout.iterdir():
            if path.name != ".git":
                if path.is_dir() and not path.is_symlink():
                    shutil.rmtree(path)
                else:
                    path.unlink()
        shutil.copytree(site, checkout, dirs_exist_ok=True)
        runner.run("git", "add", "--all")
        changed = subprocess.run(
            ["git", "diff", "--cached", "--quiet"], cwd=checkout, check=False
        ).returncode
        if changed not in (0, 1):
            raise ReleaseError("Could not compare the generated docs tree")
        if changed:
            record = json.loads((site / MARKER).read_text())
            runner.run(
                "git",
                "commit",
                "-S",
                "-s",
                "-m",
                "Publish documentation for " + record["build"]["source"][:12],
            )
        runner.run("git", "verify-commit", "HEAD")
        revision = git(checkout, "rev-parse", "HEAD")
        if changed:
            runner.run("git", "push", remote, "HEAD:" + ref)
        commit = forge.api("/git/commits/" + revision)
        if not commit.get("commit", {}).get("verification", {}).get("verified"):
            raise ReleaseError(
                "Docs pushed, but Codefloe could not verify the commit signature"
            )
        return revision


def verify_site(url, record, timeout=300):
    """Read public HTTPS without forge credentials, including every generated asset."""
    deadline = time.monotonic() + timeout
    opener = urllib.request.build_opener(NoRedirect())
    query = "?build=" + record["site_sha256"]

    def fetch(path):
        request = urllib.request.Request(
            url + urllib.parse.quote(path, safe="/") + query,
            headers={"Cache-Control": "no-cache"},
        )
        with opener.open(request, timeout=15) as response:
            return response.read()

    def verify_file(item):
        import hashlib

        path, expected = item
        if hashlib.sha256(fetch(path)).hexdigest() != expected:
            raise ReleaseError("Published docs differ: " + path)

    error = "site not available"
    while time.monotonic() < deadline:
        try:
            if json.loads(fetch(MARKER)) != record:
                raise ReleaseError(
                    "Hosted build marker is still from another deployment"
                )
            with concurrent.futures.ThreadPoolExecutor(max_workers=8) as pool:
                list(pool.map(verify_file, record["files"].items()))
            print(f"Docs verified: {url} ({len(record['files'])} files)", flush=True)
            return
        except (OSError, ValueError, ReleaseError, urllib.error.URLError) as failure:
            error = str(failure)
            remaining = deadline - time.monotonic()
            if remaining > 0:
                time.sleep(min(10, remaining))
    raise ReleaseError(
        "Docs pushed; hosted verification timed out: "
        + error
        + ". Repeat docs-deploy with the same --ref to verify/retry."
    )


def deploy(source, output, config, timeout=300, expected=None):
    url, branch = settings(config)
    token = Path(config["token_file"]).expanduser().read_text().strip()
    repository = destination(config)
    forge = Forge(repository, token, config.get("allow_public", False))
    repo = forge.repository_check()
    if (
        repository == config["repository"].rstrip("/")
        and branch == repo["default_branch"]
    ):
        raise ReleaseError("Docs cannot replace the repository default branch")
    remote = remote_url(source, config)
    clean(source)
    output.mkdir(parents=True, exist_ok=True)
    log = output / "run.log"
    record = build_site(source, output / "site", log)
    if expected and any(
        record["build"][key] != str(expected[key])
        for key in ("source", "version", "build_number")
    ):
        raise ReleaseError(
            "Docs source/build identity differs from the published release"
        )
    revision = publish_tree(source, output / "site", remote, branch, log, forge)
    write_json(
        output / "deployment.json",
        {"status": "pushed", "commit": revision, "url": url, "build": record["build"]},
    )
    print(f"Docs pushed: {revision[:12]}; checking {url}", flush=True)
    verify_site(url, record, timeout)
    write_json(
        output / "deployment.json",
        {
            "status": "verified",
            "commit": revision,
            "url": url,
            "build": record["build"],
        },
    )


def after_release(source, root, identity, config):
    if not enabled(config):
        return
    try:
        deploy(source, root / "docs", config, expected=identity)
    except (ReleaseError, OSError, ValueError, subprocess.CalledProcessError) as error:
        raise ReleaseError(
            "Release published; docs pending. Retry ./dev docs-deploy --ref "
            + identity["source"]
            + " with the same --config. "
            + str(error)
        ) from error
