//! Media storage abstraction: local disk first, with the trait boundary in
//! place for object storage later.

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::Mutex;

use crate::federation::BoxFuture;
use crate::sync::RecoverableMutex as _;

/// A seekable async reader over one stored file, for streaming/range serving.
pub trait MediaReader: tokio::io::AsyncRead + tokio::io::AsyncSeek + Send + Unpin {}
impl<T: tokio::io::AsyncRead + tokio::io::AsyncSeek + Send + Unpin> MediaReader for T {}

/// An opened stored file: its total length plus a reader positioned at the
/// start. Serving code seeks/takes on the reader instead of buffering the
/// whole file — a feature video needs (multi-GB files, HTTP ranges).
pub struct MediaRead {
    pub len: u64,
    pub reader: Box<dyn MediaReader>,
}

pub trait MediaStore: Send + Sync {
    fn put(&self, file_name: &str, bytes: Vec<u8>) -> BoxFuture<'_, std::io::Result<()>>;
    /// Moves an already-on-disk file into the store — the large-file
    /// counterpart of [`Self::put`]; the content is never buffered.
    fn put_file(
        &self,
        file_name: &str,
        src: &std::path::Path,
    ) -> BoxFuture<'_, std::io::Result<()>>;
    fn get(&self, file_name: &str) -> BoxFuture<'_, std::io::Result<Vec<u8>>>;
    /// Opens a stored file for streaming reads (see [`MediaRead`]).
    fn open(&self, file_name: &str) -> BoxFuture<'_, std::io::Result<MediaRead>>;
    /// Removes a stored file; missing files are not an error.
    fn delete(&self, file_name: &str) -> BoxFuture<'_, std::io::Result<()>>;
    /// Every stored key (flat, non-recursive) — the reconciliation sweep
    /// diffs this against the database's referenced keys to find
    /// files orphaned by pre-fix deletions. Subdirectories (e.g. the transcode
    /// scratch `tmp/`) are skipped: only files we serve live at the root.
    fn list(&self) -> BoxFuture<'_, std::io::Result<Vec<String>>>;
}

/// Flat-directory disk storage. File names are generated by us
/// (`{snowflake}.{ext}`), never taken from clients.
pub struct LocalDiskStore {
    root: PathBuf,
}

impl LocalDiskStore {
    pub fn new(root: PathBuf) -> std::io::Result<Self> {
        std::fs::create_dir_all(&root)?;
        Ok(Self { root })
    }
}

impl MediaStore for LocalDiskStore {
    fn put(&self, file_name: &str, bytes: Vec<u8>) -> BoxFuture<'_, std::io::Result<()>> {
        let path = self.root.join(file_name);
        Box::pin(async move { tokio::fs::write(path, bytes).await })
    }

    fn put_file(
        &self,
        file_name: &str,
        src: &std::path::Path,
    ) -> BoxFuture<'_, std::io::Result<()>> {
        let dest = self.root.join(file_name);
        let src = src.to_path_buf();
        Box::pin(async move {
            // Same filesystem (the A/V scratch dir lives under the media
            // root): a rename. Cross-device (operator pointed scratch
            // elsewhere): fall back to copy + remove.
            if tokio::fs::rename(&src, &dest).await.is_err() {
                tokio::fs::copy(&src, &dest).await?;
                tokio::fs::remove_file(&src).await.ok();
            }
            Ok(())
        })
    }

    fn get(&self, file_name: &str) -> BoxFuture<'_, std::io::Result<Vec<u8>>> {
        let path = self.root.join(file_name);
        Box::pin(async move { tokio::fs::read(path).await })
    }

    fn open(&self, file_name: &str) -> BoxFuture<'_, std::io::Result<MediaRead>> {
        let path = self.root.join(file_name);
        Box::pin(async move {
            let file = tokio::fs::File::open(path).await?;
            let len = file.metadata().await?.len();
            Ok(MediaRead {
                len,
                reader: Box::new(file),
            })
        })
    }

    fn delete(&self, file_name: &str) -> BoxFuture<'_, std::io::Result<()>> {
        let path = self.root.join(file_name);
        Box::pin(async move {
            match tokio::fs::remove_file(path).await {
                Err(e) if e.kind() != std::io::ErrorKind::NotFound => Err(e),
                _ => Ok(()),
            }
        })
    }

    fn list(&self) -> BoxFuture<'_, std::io::Result<Vec<String>>> {
        let root = self.root.clone();
        Box::pin(async move {
            let mut names = Vec::new();
            let mut entries = tokio::fs::read_dir(&root).await?;
            while let Some(entry) = entries.next_entry().await? {
                // Only regular files at the root are served keys; skip the
                // transcode scratch subdirectory and anything else.
                if entry.file_type().await?.is_file()
                    && let Some(name) = entry.file_name().to_str()
                {
                    names.push(name.to_owned());
                }
            }
            Ok(names)
        })
    }
}

/// In-memory store for tests.
#[derive(Default)]
pub struct MemoryStore {
    files: Mutex<HashMap<String, Vec<u8>>>,
}

impl MediaStore for MemoryStore {
    fn put(&self, file_name: &str, bytes: Vec<u8>) -> BoxFuture<'_, std::io::Result<()>> {
        self.files
            .lock()
            .unwrap()
            .insert(file_name.to_owned(), bytes);
        Box::pin(async { Ok(()) })
    }

    fn put_file(
        &self,
        file_name: &str,
        src: &std::path::Path,
    ) -> BoxFuture<'_, std::io::Result<()>> {
        let file_name = file_name.to_owned();
        let src = src.to_path_buf();
        Box::pin(async move {
            let bytes = tokio::fs::read(&src).await?;
            tokio::fs::remove_file(&src).await.ok();
            self.files.lock_or_recover().insert(file_name, bytes);
            Ok(())
        })
    }

    fn get(&self, file_name: &str) -> BoxFuture<'_, std::io::Result<Vec<u8>>> {
        let found = self.files.lock_or_recover().get(file_name).cloned();
        Box::pin(async move {
            found.ok_or_else(|| std::io::Error::new(std::io::ErrorKind::NotFound, "no such file"))
        })
    }

    fn open(&self, file_name: &str) -> BoxFuture<'_, std::io::Result<MediaRead>> {
        let found = self.files.lock_or_recover().get(file_name).cloned();
        Box::pin(async move {
            let bytes = found
                .ok_or_else(|| std::io::Error::new(std::io::ErrorKind::NotFound, "no such file"))?;
            Ok(MediaRead {
                len: bytes.len() as u64,
                reader: Box::new(std::io::Cursor::new(bytes)),
            })
        })
    }

    fn delete(&self, file_name: &str) -> BoxFuture<'_, std::io::Result<()>> {
        self.files.lock_or_recover().remove(file_name);
        Box::pin(async { Ok(()) })
    }

    fn list(&self) -> BoxFuture<'_, std::io::Result<Vec<String>>> {
        let names = self.files.lock_or_recover().keys().cloned().collect();
        Box::pin(async move { Ok(names) })
    }
}
